name: test-env
channels:
  - defaults
dependencies:
  - pip=25.2
  - python=3.12.12
  - pip:
      - datasets==4.4.1
      - numpy==2.3.4
      - pandas==2.3.3
      - pillow==12.0.0
      - pyyaml==6.0.3
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - tokenizers==0.22.1
      - torch==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - pytest==8.4.2
      - pytest-mock==3.15.1
