name: mlops
channels:
  - defaults
dependencies:
  - python=3.12.12
  - numpy=2.3.5
  - pandas=2.3.3
  - pillow=12.0.0
  - pytest=8.4.2
  - pyyaml=6.0.3
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - tqdm=4.67.1
  - pip
  - pip:
      - torch==2.9.1
      - torchvision==0.24.1
      - transformers==4.57.3
      - datasets==4.4.2
      - tokenizers==0.22.2
      - pytest-mock==3.15.1
      - dvc==3.66.1
      - dvc-s3==3.2.2
      - boto3==1.41.5
      - mlflow==3.8.1