name: test-env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python==3.12.12
  - pip==25.2
  - cpuonly
  - pytorch==2.2.2
  - torchvision==0.17.2
  - numpy==1.26
  - transformers==4.57.1
  - datasets==4.4.1
  - scikit-learn==1.7.2
  - pyyaml==6.0.3
  - tqdm==4.67.1
  - pillow==12.0.0
  - pytest==8.4.2
  - pytest-mock==3.15.1
  - pandas==2.3.3
  - scipy==1.16.3
  - tokenizers==0.22.1